#!/usr/bin/env bash
# script installs and restarts nginx
sudo apt-get -y install nginx
service nginx start
ufw allow 'Nginx HTTP'
echo "Hello World!\n" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart