#!/usr/bin/env bash
# shellcheck disable=SC2154
# Bash script that configure Nginx so that its HTTP response contains a custom header

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html

header_str="location \/ {\n\t\tadd_header X-Served-By \$hostname;"
sudo sed -i "s/location \/ {/$header_str/" /etc/nginx/sites-available/default

sudo service nginx restart
