#!/usr/bin/env bash
# Bash script that install and configure HAproxy

CONF="\
frontend striker_balancer
    bind *:80
    mode http
    default_backend striker
backend striker
    balance roundrobin
    server 475-web-01 34.138.198.236 check
    server 475-web-02 3.80.231.46 check
"
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo echo "$CONF" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start

