#!/usr/bin/env bash
#  Script bash FizzBuzz
conter=1
while [ $conter -le 100 ];
do
    if [ $((conter%3)) -eq 0 ] && [ $((conter%5)) -eq 0 ];
    then
        echo "FizzBuzz"
    elif [ $((conter%3)) -eq 0 ];
    then
        echo "Fizz"
    elif [ $((conter%5)) -eq 0 ];
    then
        echo "Buzz"
    else
        echo $conter
    fi
    conter=$((conter + 1))
done