#!/usr/bin/env bash
# displays numbers from 1 to 20, 4 china, 9 japan, 17 italy 
i=1
while [ $i -le 20 ]; do
	echo "$i"
	case $i in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
		*)
			;;
	esac
	let "i++"
done
