#!/usr/bin/env bash
# configuration of ubuntu servers
# It resolves localhost to 127.0.0.2
cp /etc/hosts ~/hosts.new
sed -i "s/127.0.0.1/127.0.0.2/g" ~/hosts.new
# It resolves facebook.com  to 8.8.8.8
sed -i "\$a 8.8.8.8 facebook.com" ~/hosts.new
cp -f ~/hosts.new /etc/hosts

